version: '3.8'
services:
  frontend:
    build:
      context: ./frontend # Path to your Angular project
      dockerfile: Dockerfile
    ports:
      - '80:80' # Map host port 80 to container port 80
    networks:
      - app-network

  backend:
    build:
      context: ./backend # Path to your C# project
      dockerfile: Dockerfile
    ports:
      - '8080:8080' # Map host port 8080 to container port 8080 (or your chosen backend port)
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
